### ISSUE TITLE
yep, I'm interested

### ISSUE THREAD

**Issue by richardhundt** [mbuhot/eskotlin#1]
I noticed you post on reddit asking if anyone was interested 👍 

Your project has a mention on elastic.co as a community Kotlin client. It's the only one on their list for Kotlin, so it's kinda visible, and it's looking really nice. Any plans to get it feature complete?

Cheers and thanks for what you've done so far!

**Comment by mbuhot** [comment]
Hi Richard,

Thanks for checking out the repo. This is my first attempt at a Kotlin DSL, so just a code review would be much appreciated!

Feature wise, I think the Geo queries would be a nice addition, but basically any missing functionality that you'd like to see in this client would be great.

It's hopefully simple to add new functionality.
I've tried to stick to the same pattern in every file, and test by rendering to JSON.

**Comment by richardhundt** [comment]
I'm pretty new to Kotlin, so I'm really not the best person to critique your code, however from what I've seen it looks pretty nicely structured.

+1 for geo queries.

In terms of features, many folks use elasticsearch as an analytics engine, so aggregations are vital and seem to be missing entirely? Perhaps I've missed them in the sources. I also use scripting quite heavily, again because for me it's firstly an analytics tool.

HTH

**Comment by mbuhot** [comment]
Good idea on aggregations. The simple ones such as [average](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html#search-aggregations-metrics-avg-aggregation) should be simple to create some DSL functions for.

**Comment by jamesbassett** [comment]
Congrats on the elastic.co mention @mbuhot :)  Too bad there's already an elixir client!

**Comment by mbuhot** [comment]
@jamesbassett shhh, I submitted that link myself because there wasn't already a Kotlin client ;)
