### ISSUE TITLE
development status? 

### ISSUE THREAD

**Issue by wenhoujx** [mbuhot/eskotlin#19]
hi the last contribution was month ago, i wonder what's the current status of this project. 

I'd like to contribute, but not sure what's the plan.

**Comment by mbuhot** [comment]
Hi @wenhoujx, I'm not using Kotlin or Elasticsearch in my day job at the moment, so I'm not actively developing eskotlin, just responding to issues and PRs as they are raised.

I think the features that are implemented work well - they simply wrap the Java API.

What would you like to add?

**Comment by wenhoujx** [comment]
hi @mbuhot  , i am interested in if there is plan to add admin apis that manages index mapping, creation, settings .. etc

**Comment by mbuhot** [comment]
@wenhoujx admin APIs that could be used from a kotlin script would be nice. How are you managing those in your projects today? Maybe pick one task that you perform regularly and open a separate issue for adding an admin API for it.
