### ISSUE TITLE
Use camelCase function names

### ISSUE THREAD

**Issue by heinrichreimer** [mbuhot/eskotlin#26]
The usage of snake_case function names is unidiomatic in Java/Kotlin.
We might consider to deprecate those functions in this DSL and instead use camelCase-named functions, e.g. `matchAll` instead of `match_all`.

**Comment by mbuhot** [comment]
Thanks for the suggestion.

The goal of this library has always been to mimic the JSON Query DSL, even if it means the function names are not idiomatic Java/Kotlin.

Before making such a significant change to the API, it would be great to get some feedback from other users.

@puug / @vincentlauvlwj what are your thoughts?

**Comment by heinrichreimer** [comment]
Olay, that might be just different priorities for you and me.
While you prefer to  mimic the JSON as close as possible, I would like to keep code as short as possible, leveraging Kotlin language features, like the range operator I suggested [in another issue](https://github.com/mbuhot/eskotlin/issues/27).

So you're right about it being a major change and I agree it should be discussed (hence this issue).

We could also support both.
